### ISSUE TITLE
Log function not working

### ISSUE THREAD

**Issue by maymoo99** [hakaru-dev/hakaru#118]
Getting the following error when trying to use the log() function

```
hakaru: TODO: evaluatePrimOp{Log}
CallStack (from HasCallStack):
  error, called at haskell/Language/Hakaru/Sample.hs:375:5 in hakaru-0.6.0-AbnzUW5EnqjBuQmLn3LJbU:Language.Hakaru.Sample
```

**Comment by zaxtax** [comment]
We never implemented log in Language.Hakaru.Sample.hs

The relevant case needs to be added to the evaluatePrimOp function

On Nov 22, 2017 03:01, "maymoo99" <notifications@github.com> wrote:

Getting the following error when trying to use the log() function

hakaru: TODO: evaluatePrimOp{Log}
CallStack (from HasCallStack):
  error, called at haskell/Language/Hakaru/Sample.hs:375:5 in
hakaru-0.6.0-AbnzUW5EnqjBuQmLn3LJbU:Language.Hakaru.Sample

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hakaru-dev/hakaru/issues/118>, or mute the thread

**Comment by maymoo99** [comment]
Implemented and pulled
