### ISSUE TITLE
Non-implemented simplification

### ISSUE THREAD

**Issue by JacquesCarette** [hakaru-dev/hakaru#22]
Test t57, namely
fn t real:
  (if (t < 1):
     return ()
   else:
     reject. measure(unit)) <|>
  (if (t > 0):
     return ()
   else:
     reject. measure(unit))

does not 'simplify' to what is wanted.  The crux of the matter is that, in operator notation in Maple,
   Indicator(t<1) \* m + Indicator(0<t) \* m
for any measure m, does not simplify.

Should it?  Note that
simplify(piecewise(t<1,1,0) + piecewise(0<t,1,0));
           piecewise(t <= 0, 1, t < 1, 2, 1 <= t, 1)
so Maple certainly can do that.  However, there is also that
simplify(piecewise(t<1,1,0)_m + piecewise(0<t,1,0)_m);
          piecewise(t <= 0, m, t < 1, 2 m, 1 <= t, m)

which turns a data piecewise into a control piecewise, which is likely unwanted.

So, what is the right design?

**Comment by yuriy0** [comment]
This happened to be related to a fairly recent (I believe) issue with Partition, which I was reminded of and decided to fix (6e3af0f7e). For posterity, the issue was Partition:-Simpl at some point gained the ability to simplify sums and products of partitions (which would simplify the expression in t57); but this wasn't used in `reduce`, because `Partition:-Simpl` would only ever be applied to a partition (never a sum or product of partitions). It seems to have the desired property of not "turn[ing] a data piecewise into a control piecewise".

**Comment by JacquesCarette** [comment]
Excellent.  This closes that issue too.
