### ISSUE TITLE
Hashable instances for AST types

### ISSUE THREAD

**Issue by sabauma** [hakaru-dev/hakaru#40]
`Hashable` instances for the Hakaru AST types would allow the use of fast associative containers for AST transformations (say, CSE). This would probably have to work on the full AST in order to support equivalence of terms like `summate`. Perhaps GHC can derive much of the implementation though?

**Comment by zaxtax** [comment]
It's worth a shot!

**Comment by sabauma** [comment]
Our resident expert on `GHC.Generics` has indicated that it is not possible for GHC to derive `Generic` instances for most interesting GADTs.  The current method for getting free `Hashable` instances relies on `Generic` instances for your data types. This is unfortunate as there are quite a few `Hashable` instances which need to be written, most of are the obvious, mechanical code snippets.

The only interesting instances would be for ABTs and Variables, since what we want are hashes which preserve alpha equivalence.

**Comment by wrengr** [comment]
> The only interesting instances would be for ABTs and Variables, since what we want are hashes which preserve alpha equivalence.

To get alpha-equivalent terms to be hash-equal, you'll need to do some sort of name canonicalization first (e.g., De Bruijn indices). Of course, depending on how exactly you do name canonicalization, you probably won't get nice compositional hashes via the `Hashable` interface (i.e., implemented with a function of type `a -> Int`).

But there's no especial reason to require the `Hashable` interface just because you're taking a "hash-based" approach. You can always just implement a wrapper around `IntMap` or whathaveyou. This would free you up to implement a hash function that's smarter than `a -> Int` allows.

**Comment by zaxtax** [comment]
I don't think we are going to do this.
