### ISSUE TITLE
Find a way to reproduce error Ken gets

### ISSUE THREAD

**Issue by JacquesCarette** [hakaru-dev/hakaru#49]
On 2017-03-03 16:35 , Chung-chieh Shan wrote:
> One reason that I classified maple/NewSLOTest.mpl as worthy of attention
> is I got the following just now:
>
>      Error, (in assuming) when calling 'simplify/siderels:-simplify/siderels'.
>      Received: 'side relations must be polynomials in (name or function) variables'

I tried on karst (which has Maple 2016) and could not reproduce.

**Comment by ccshan** [comment]
On 2017-04-03T18:20:07-0700, Jacques Carette wrote:
> On 2017-03-03 16:35 , Chung-chieh Shan wrote:
> > One reason that I classified maple/NewSLOTest.mpl as worthy of attention
> > is I got the following just now:
> >
> >      Error, (in assuming) when calling 'simplify/siderels:-simplify/siderels'.
> >      Received: 'side relations must be polynomials in (name or function) variables'
> 
> I tried on karst (which has Maple 2016) and could not reproduce.

Hmm!  Could it be because I have the latest maintenance update (2016.2)
on my laptop?

    laptop$ maple -q -c 'version()' </dev/null
     User Interface: 1194701
             Kernel: 1194701
            Library: 1194701

    karst$ maple -q -c 'version()' </dev/null
     User Interface: 1133417
             Kernel: 1133417
            Library: 1133417

Let me know if it would help for you to get Maple through IU.  Thanks!

**Comment by JacquesCarette** [comment]
Yes, it could be because of the update.  Yes, getting me a version of Maple2016 would help track these things down.

**Comment by ccshan** [comment]
On 2017-04-03T19:57:55-0700, Jacques Carette wrote:
> Yes, it could be because of the update.  Yes, getting me a version of Maple2016 would help track these things down.

For which OS would you like a Maple 2016 license?

**Comment by JacquesCarette** [comment]
OSX please.

**Comment by JacquesCarette** [comment]
Double success: I can reproduce this on Maple2016.2.

**Comment by yuriy0** [comment]
I was only able to reproduce this in one test case (slice sampling Gaussian(0,1)). That occurence should be fixed by 0f3742ee9.

I think that on older versions of Maple, `coulditbe` would simply return `FAIL` when it found "side relations" which are not "polynomials in (name or function) variables", but 2016.2 errors instead. In the test case that threw this, the particular constraint that causes it is something like `u < ... ln(..) ..`; the LHS is already a variable so KB is in a good place to manipulate it already; nor does this particular case actually make the KB false, so the `coulditbe` isn't 'useful'. 

If someone can confirm that was the only occurrence of this bug, this issue can be closed.

**Comment by JacquesCarette** [comment]
I can verify that this is fixed.
